name: CI

on:
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .[dev]; fi
          pip install pre-commit

      - name: Ruff (lint + format check)
        run: |
          ruff check .
          ruff format --check .

      - name: Pytest
        env:
          PYTHONWARNINGS: default
        run: pytest -q

      - name: pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure
