services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: mhe
      POSTGRES_USER: mhe
      POSTGRES_PASSWORD: mhe
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "mhe"]
      interval: 5s
      timeout: 5s
      retries: 20
