version: '3.8'

services:
  desktop-commander:
    build:
      context: ../../
      dockerfile: docker/desktop-commander/Dockerfile
    container_name: mhe-desktop-commander
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    user: "1000:1000"
    environment:
      - NODE_ENV=production
      - WORKSPACE=${WORKSPACE:-/workspace}
    volumes:
      - ${WORKSPACE:-$(pwd)}:/workspace:ro
      - /tmp:/tmp:rw
    working_dir: /workspace
    networks:
      - mhe-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mhe-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"